# --- Archivo de Configuración para el Scraper del IDSE ---
#
# Instrucciones:
# 1. Reemplaza los valores de ejemplo con tus datos reales.
# 2. IMPORTANTE: Utiliza rutas absolutas para tus archivos .cer y .key.
#
#    - Ejemplo de ruta en Windows: C:\Users\TuUsuario\Documentos\IMSS\certificado.cer
#    - Ejemplo de ruta en macOS/Linux: /home/tu_usuario/documentos/imss/certificado.cer

[IMSS_CREDENCIALES]
RUTA_CER = /Users/jesusgallegosontiveros/Downloads/Z4230873102.cer
RUTA_KEY = /Users/jesusgallegosontiveros/Downloads/Z4230873102.key
USUARIO = SEI250429R94
CONTRASENA_SITIO = WaLdos29#

[SELENIUM]
RUTA_DRIVER = /Users/jesusgallegosontiveros/Documents/Proyectos/scraper/msedgedriver